name: CI
on: 
  push:
    # Sequence of patterns matched against refs/heads
    # branches:    
    #   - main
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Env
        run: |
          echo "VERSION=$(cat ./version.txt)" >> $GITHUB_ENV
          echo "VERSION=$(cat ./version.txt)"
      
