name: CI
on: [push]

jobs:
  release:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Env
        run: |
          echo "VERSION=$(cat ./version.txt)" >> $GITHUB_ENV
          echo "VERSION=$(cat ./version.txt)"
      
