name: Release
on: 
  push:
    # Sequence of patterns matched against refs/heads
    # branches:    
    #   - main
    # Sequence of patterns matched against refs/tags
    tags:        
      - v*

jobs:
  test:
      uses: ./.github/workflows/test.yml
      secrets: inherit
  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Version Env
        run: |
          echo "VERSION=$(cat ./version.txt)" >> $GITHUB_ENV
          echo "VERSION=$(cat ./version.txt)"
      - name: Release
        run: |
          echo "Version $VERSION released." 
      
