name: Test
on: 
  workflow_call:
  push:
    # Sequence of patterns matched against refs/heads
    branches:    
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          echo "VERSION=$(cat ./version.txt)" >> $GITHUB_ENV
          echo "running test..."
      
